const API="https://nationalbank.kz/rss/rates_all.xml",CUR={KZT:"Казахстанский тенге",RUB:"Российский рубль",USD:"Доллар США",EUR:"Евро",CNY:"Китайский юань"},$=s=>document.querySelector(s),store=chrome.storage.local;
const amount=$("#amount"),from=$("#from"),to=$("#to"),out=$("#result"),rate=$("#rate"),error=$("#error"),status=$("#status"),theme=$("#theme");let rates;
for(const [code,name] of Object.entries(CUR)){from.add(new Option(`${code} — ${name}`,code));to.add(new Option(`${code} — ${name}`,code))}from.value="KZT";to.value="USD";
const get=k=>new Promise(done=>store.get(k,done)),set=v=>new Promise(done=>store.set(v,done));
function setTheme(value){const dark=value==="dark";document.body.classList.toggle("dark",dark);theme.textContent=dark?"☀":"☾";theme.title=dark?"Включить светлую тему":"Включить тёмную тему"}
function money(value,currency){return new Intl.NumberFormat("ru-KZ",{style:"currency",currency,maximumFractionDigits:value>=100?2:4}).format(value)}
function calculate(){error.textContent="";const n=Number(amount.value.trim().replace(/\s/g,"").replace(",","."));if(!Number.isFinite(n)||n<0){out.textContent="—";rate.textContent="";error.textContent="Введите корректную положительную сумму";return}if(!rates)return;const unit=rates[from.value]/rates[to.value],value=n*unit;out.textContent=money(value,to.value);rate.textContent=`1 ${from.value} = ${new Intl.NumberFormat("ru-KZ",{maximumFractionDigits:6}).format(unit)} ${to.value}`}
function parse(xml){const doc=new DOMParser().parseFromString(xml,"application/xml");if(doc.querySelector("parsererror"))throw Error("Некорректный ответ НБК");const map={KZT:1};for(const item of doc.querySelectorAll("item")){const code=item.querySelector("title")?.textContent?.trim();if(!CUR[code])continue;const price=Number(item.querySelector("description")?.textContent?.trim().replace(",",".")),q=Number(item.querySelector("quant")?.textContent?.trim()||1);if(price>0&&q>0)map[code]=price/q}if(Object.keys(CUR).some(c=>!map[c]))throw Error("В ответе НБК нет нужного курса");return{map,date:doc.querySelector("item > pubDate")?.textContent?.trim()||new Date().toLocaleDateString("ru-KZ")}}
async function load(force=false){$("#refresh").disabled=true;try{const cached=(await get("rates"))?.rates;if(!force&&cached&&Date.now()-cached.saved<21600000){rates=cached.map;status.textContent=`Курс НБК на ${cached.date}`;calculate();return}const res=await fetch(API,{cache:"no-store"});if(!res.ok)throw Error(`Ошибка HTTP ${res.status}`);const parsed=parse(await res.text());rates=parsed.map;await set({rates:{...parsed,saved:Date.now()}});status.textContent=`Курс НБК на ${parsed.date}`;calculate()}catch(e){const cached=(await get("rates"))?.rates;if(cached){rates=cached.map;status.textContent=`Сохранённый курс на ${cached.date}`;error.textContent="Не удалось обновить курс";calculate()}else{status.textContent="Курс недоступен";error.textContent=e.message}}finally{$("#refresh").disabled=false}}
amount.addEventListener("input",calculate);from.addEventListener("change",calculate);to.addEventListener("change",calculate);$("#swap").addEventListener("click",()=>{[from.value,to.value]=[to.value,from.value];calculate()});$("#refresh").addEventListener("click",()=>load(true));theme.addEventListener("click",async()=>{const value=document.body.classList.contains("dark")?"light":"dark";setTheme(value);await set({theme:value})});get("theme").then(v=>setTheme(v.theme||(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light")));load();
